import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSbusesSchema1778352066036 implements MigrationInterface {
    name = 'InitSbusesSchema1778352066036'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`grupo_persona\` (\`id\` varchar(36) NOT NULL, \`persona_id\` varchar(36) NULL, \`grupo_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`grupo\` (\`id\` varchar(36) NOT NULL, \`nombre\` varchar(255) NOT NULL, \`descripcion\` varchar(255) NOT NULL, \`fechaCreacion\` datetime NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`destinatario_grupo\` (\`id\` varchar(36) NOT NULL, \`mensaje_id\` varchar(36) NULL, \`grupo_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`mensaje\` (\`id\` varchar(36) NOT NULL, \`contenido\` varchar(255) NOT NULL, \`fechaEnvio\` timestamp NOT NULL, \`tipo\` enum ('PQRS', 'Reporte de Incidentes', 'Mensaje normal') NOT NULL DEFAULT 'Mensaje normal', \`emisor_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`destinatario_persona\` (\`id\` varchar(36) NOT NULL, \`leido\` tinyint NOT NULL DEFAULT 0, \`mensaje_id\` varchar(36) NULL, \`persona_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ruta_paradero\` (\`id\` varchar(36) NOT NULL, \`orden\` int NOT NULL, \`distancia_desde_anterior\` decimal(10,2) NULL, \`tiempo_estimado\` int NULL, \`ruta_id\` varchar(36) NOT NULL, \`paradero_id\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`paradero\` (\`id\` varchar(36) NOT NULL, \`codigo\` varchar(255) NOT NULL, \`nombre\` varchar(255) NOT NULL, \`latitud\` decimal(10,7) NOT NULL, \`longitud\` decimal(10,7) NOT NULL, \`tipo\` varchar(255) NULL, \`estado\` tinyint NOT NULL DEFAULT 1, \`nodo_id\` varchar(36) NOT NULL, UNIQUE INDEX \`IDX_a47bf8f07546ec7ce88ba4f027\` (\`codigo\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`nodo\` (\`id\` varchar(36) NOT NULL, \`latitud\` decimal(10,7) NOT NULL, \`longitud\` decimal(10,7) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ruta_nodo\` (\`id\` varchar(36) NOT NULL, \`orden\` int NOT NULL, \`ruta_id\` varchar(36) NOT NULL, \`nodo_id\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ruta\` (\`id\` varchar(36) NOT NULL, \`codigo\` varchar(255) NOT NULL, \`nombre\` varchar(255) NOT NULL, \`descripcion\` varchar(255) NULL, \`tarifa\` decimal(10,2) NOT NULL, \`tiempo_estimado_total\` int NULL, \`estado\` tinyint NOT NULL DEFAULT 1, UNIQUE INDEX \`IDX_1e33ae47cf8a8048e14db83ebc\` (\`codigo\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`empresa\` (\`id\` varchar(36) NOT NULL, \`nombre\` varchar(255) NOT NULL, \`nit\` varchar(255) NOT NULL, UNIQUE INDEX \`IDX_51ac4482e14d7afaa64eab9c5a\` (\`nit\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`gps\` (\`id\` varchar(36) NOT NULL, \`latitud\` int NOT NULL, \`longitud\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`bus_id\` varchar(36) NULL, UNIQUE INDEX \`REL_8f4db1f562e86ccd755281edc6\` (\`bus_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`incidente\` (\`id\` varchar(36) NOT NULL, \`tipo\` enum ('Mecánico', 'Accidente', 'Retraso', 'Otro') NOT NULL, \`gravedad\` enum ('Bajo', 'Medio', 'Alto', 'Crítico') NOT NULL, \`descripcion\` text NULL, \`seguimiento_log\` text NULL, \`estado\` enum ('Pendiente', 'En_Revision', 'Resuelto') NOT NULL DEFAULT 'Pendiente', \`latitud\` decimal(10,7) NOT NULL, \`longitud\` decimal(10,7) NOT NULL, \`fecha_reporte\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`foto\` (\`id\` varchar(36) NOT NULL, \`url\` varchar(255) NOT NULL, \`incidente_bus_id\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`incidente_bus\` (\`id\` varchar(36) NOT NULL, \`incidente_id\` varchar(36) NOT NULL, \`bus_id\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`bus\` (\`id\` varchar(36) NOT NULL, \`placa\` varchar(255) NOT NULL, \`modelo\` varchar(255) NOT NULL, \`anio\` int NOT NULL, \`capacidad_total\` int NOT NULL, \`capacidad_sentados\` int NOT NULL, \`capacidad_parados\` int NOT NULL, \`estado\` enum ('Operativo', 'Mantenimiento', 'Fuera_Servicio') NOT NULL DEFAULT 'Operativo', \`foto_url\` varchar(255) NULL, \`qr_code\` varchar(255) NULL, \`empresa_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_fb7ea3a64d22d5276573f22dbd\` (\`placa\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`programacion\` (\`id\` varchar(36) NOT NULL, \`fecha\` date NOT NULL, \`hora_salida\` time NOT NULL, \`tolerancia_minutos\` int NOT NULL DEFAULT '0', \`pasajeros_actuales\` int NOT NULL DEFAULT '0', \`tipo_recurrencia\` enum ('Diaria', 'Laboral', 'Fin_Semana') NOT NULL, \`estado\` enum ('Programado', 'En_Curso', 'Finalizado') NOT NULL DEFAULT 'Programado', \`ruta_id\` varchar(36) NOT NULL, \`bus_id\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`metodo_pago\` (\`id\` varchar(36) NOT NULL, \`tipo\` enum ('Tarjeta', 'Efectivo', 'ePayco') NOT NULL, \`descripcion\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`metodo_pago_ciudadano\` (\`id\` varchar(36) NOT NULL, \`metodo_pago_id\` varchar(36) NULL, \`ciudadano_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`historial\` (\`id\` varchar(36) NOT NULL, \`tipo\` enum ('VIAJE', 'RECARGA', 'AJUSTE') NOT NULL, \`monto\` decimal(10,2) NOT NULL, \`referencia_externa\` varchar(255) NULL, \`fecha\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`boleto_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`boleto\` (\`id\` varchar(36) NOT NULL, \`hora_abordaje\` timestamp NULL, \`hora_descenso\` timestamp NULL, \`estado\` enum ('Activo', 'Completado', 'Cancelado') NOT NULL DEFAULT 'Activo', \`monto_pagado\` decimal(10,2) NOT NULL, \`qr_validacion\` varchar(255) NULL, \`ciudadano_id\` varchar(36) NOT NULL, \`programacion_id\` varchar(36) NOT NULL, \`metodo_pago_id\` varchar(36) NOT NULL, \`paradero_abordaje_id\` varchar(36) NOT NULL, \`paradero_descenso_id\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`direccion\` (\`id\` int NOT NULL AUTO_INCREMENT, \`calle\` varchar(255) NOT NULL, \`ciudad\` varchar(255) NOT NULL, \`pais\` varchar(255) NOT NULL, \`ciudadano_id\` varchar(36) NULL, UNIQUE INDEX \`REL_df373932bc5a6a0bbaaecbccea\` (\`ciudadano_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ciudadano\` (\`id\` varchar(36) NOT NULL, \`persona_id\` varchar(36) NULL, UNIQUE INDEX \`REL_fdadb55def4c5fbce66f3d392a\` (\`persona_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`personas\` (\`id\` varchar(36) NOT NULL, \`auth_id\` varchar(255) NOT NULL, \`first_name\` varchar(255) NOT NULL, \`last_name\` varchar(255) NOT NULL, \`phone\` varchar(255) NULL, \`email\` varchar(255) NOT NULL, \`tipoDocumento\` enum ('CC', 'TI', 'CE', 'PAS') NOT NULL, \`numeroDocumento\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_cabd31e2b3c629c2060912e972\` (\`auth_id\`), UNIQUE INDEX \`IDX_6019651944f62d09f56ff66f60\` (\`email\`), UNIQUE INDEX \`IDX_22bb7195753df2b9f436e5b146\` (\`numeroDocumento\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`conductores\` (\`id\` varchar(36) NOT NULL, \`licencia\` varchar(20) NOT NULL, \`activo\` tinyint NOT NULL DEFAULT 1, \`persona_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_a01e7172ea361195be58ab5962\` (\`licencia\`), UNIQUE INDEX \`REL_bc0266d66cf1bb0692fe14a01c\` (\`persona_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`turnos\` (\`id\` varchar(36) NOT NULL, \`fecha_inicio_programada\` timestamp NOT NULL, \`fecha_fin_programada\` timestamp NOT NULL, \`fecha_inicio_real\` timestamp NULL, \`fecha_fin_real\` timestamp NULL, \`estado\` enum ('PROGRAMADO', 'EN_CURSO', 'FINALIZADO') NOT NULL DEFAULT 'PROGRAMADO', \`observaciones\` text NULL, \`conductor_id\` varchar(36) NULL, \`bus_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`conductor_empresa\` (\`conductoresId\` varchar(36) NOT NULL, \`empresaId\` varchar(36) NOT NULL, INDEX \`IDX_c8f8f2fd18cb662774e35dd2b5\` (\`conductoresId\`), INDEX \`IDX_4f1cf62ca97167ffc297dc1ff6\` (\`empresaId\`), PRIMARY KEY (\`conductoresId\`, \`empresaId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`grupo_persona\` ADD CONSTRAINT \`FK_9ea3f0fa83ef78bb8294060216a\` FOREIGN KEY (\`persona_id\`) REFERENCES \`personas\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`grupo_persona\` ADD CONSTRAINT \`FK_ebc9bb021507e8b8c644bf78ea2\` FOREIGN KEY (\`grupo_id\`) REFERENCES \`grupo\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`destinatario_grupo\` ADD CONSTRAINT \`FK_c7f0f15e7fa8ca157302017f13f\` FOREIGN KEY (\`mensaje_id\`) REFERENCES \`mensaje\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`destinatario_grupo\` ADD CONSTRAINT \`FK_2c808d4acbc54788ffe55e9189b\` FOREIGN KEY (\`grupo_id\`) REFERENCES \`grupo\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mensaje\` ADD CONSTRAINT \`FK_b1d45e3d87c8eee37bc4e2b21ff\` FOREIGN KEY (\`emisor_id\`) REFERENCES \`personas\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`destinatario_persona\` ADD CONSTRAINT \`FK_7fa2d6e9f046968c997957edd10\` FOREIGN KEY (\`mensaje_id\`) REFERENCES \`mensaje\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`destinatario_persona\` ADD CONSTRAINT \`FK_beea970ff14af9f3a15fcb0f19c\` FOREIGN KEY (\`persona_id\`) REFERENCES \`personas\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ruta_paradero\` ADD CONSTRAINT \`FK_72d54fccf60b6ea346ad3dc4469\` FOREIGN KEY (\`ruta_id\`) REFERENCES \`ruta\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ruta_paradero\` ADD CONSTRAINT \`FK_3060cb5c90d2504a25523504377\` FOREIGN KEY (\`paradero_id\`) REFERENCES \`paradero\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`paradero\` ADD CONSTRAINT \`FK_dcdf9847867f04a91df1d7fe5a2\` FOREIGN KEY (\`nodo_id\`) REFERENCES \`nodo\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ruta_nodo\` ADD CONSTRAINT \`FK_50541059952803106dddc9e6aa0\` FOREIGN KEY (\`ruta_id\`) REFERENCES \`ruta\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ruta_nodo\` ADD CONSTRAINT \`FK_eee2cae961894022e049d8a13fc\` FOREIGN KEY (\`nodo_id\`) REFERENCES \`nodo\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`gps\` ADD CONSTRAINT \`FK_8f4db1f562e86ccd755281edc60\` FOREIGN KEY (\`bus_id\`) REFERENCES \`bus\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`foto\` ADD CONSTRAINT \`FK_c4fd0e65ba0905cb36931c0b78c\` FOREIGN KEY (\`incidente_bus_id\`) REFERENCES \`incidente_bus\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`incidente_bus\` ADD CONSTRAINT \`FK_58c5047804eba8562637d817c5c\` FOREIGN KEY (\`incidente_id\`) REFERENCES \`incidente\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`incidente_bus\` ADD CONSTRAINT \`FK_61db9713f26ed84bf3087522f66\` FOREIGN KEY (\`bus_id\`) REFERENCES \`bus\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bus\` ADD CONSTRAINT \`FK_93ff3c614d8a889bb6d310ed3a2\` FOREIGN KEY (\`empresa_id\`) REFERENCES \`empresa\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`programacion\` ADD CONSTRAINT \`FK_1fefc0e6ae411f0be01cd22a484\` FOREIGN KEY (\`ruta_id\`) REFERENCES \`ruta\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`programacion\` ADD CONSTRAINT \`FK_51ba4fea596d405565625520a21\` FOREIGN KEY (\`bus_id\`) REFERENCES \`bus\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`metodo_pago_ciudadano\` ADD CONSTRAINT \`FK_3448ebaef063722c5900c2fac68\` FOREIGN KEY (\`metodo_pago_id\`) REFERENCES \`metodo_pago\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`metodo_pago_ciudadano\` ADD CONSTRAINT \`FK_16416e7ac48e2b3bb6898d1080c\` FOREIGN KEY (\`ciudadano_id\`) REFERENCES \`ciudadano\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`historial\` ADD CONSTRAINT \`FK_50bd5f52ae58b1b2efc83d5f834\` FOREIGN KEY (\`boleto_id\`) REFERENCES \`boleto\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`boleto\` ADD CONSTRAINT \`FK_c5318ccf8289d5deb313d19bd3a\` FOREIGN KEY (\`ciudadano_id\`) REFERENCES \`ciudadano\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`boleto\` ADD CONSTRAINT \`FK_60cd723c3b608aaa0059b46a909\` FOREIGN KEY (\`programacion_id\`) REFERENCES \`programacion\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`boleto\` ADD CONSTRAINT \`FK_9e9d89c940f3e190d66cf1868d5\` FOREIGN KEY (\`metodo_pago_id\`) REFERENCES \`metodo_pago_ciudadano\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`boleto\` ADD CONSTRAINT \`FK_b3182517ed67a8d0739e2c9ca59\` FOREIGN KEY (\`paradero_abordaje_id\`) REFERENCES \`paradero\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`boleto\` ADD CONSTRAINT \`FK_825ae17acb796f8a8d4b2aed798\` FOREIGN KEY (\`paradero_descenso_id\`) REFERENCES \`paradero\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`direccion\` ADD CONSTRAINT \`FK_df373932bc5a6a0bbaaecbccea7\` FOREIGN KEY (\`ciudadano_id\`) REFERENCES \`ciudadano\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ciudadano\` ADD CONSTRAINT \`FK_fdadb55def4c5fbce66f3d392a4\` FOREIGN KEY (\`persona_id\`) REFERENCES \`personas\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conductores\` ADD CONSTRAINT \`FK_bc0266d66cf1bb0692fe14a01c6\` FOREIGN KEY (\`persona_id\`) REFERENCES \`personas\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`turnos\` ADD CONSTRAINT \`FK_3db03ec6ba62996743b23a24b7e\` FOREIGN KEY (\`conductor_id\`) REFERENCES \`conductores\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`turnos\` ADD CONSTRAINT \`FK_321cdd32b08af8ecab080d49f04\` FOREIGN KEY (\`bus_id\`) REFERENCES \`bus\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`conductor_empresa\` ADD CONSTRAINT \`FK_c8f8f2fd18cb662774e35dd2b5c\` FOREIGN KEY (\`conductoresId\`) REFERENCES \`conductores\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`conductor_empresa\` ADD CONSTRAINT \`FK_4f1cf62ca97167ffc297dc1ff6c\` FOREIGN KEY (\`empresaId\`) REFERENCES \`empresa\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`conductor_empresa\` DROP FOREIGN KEY \`FK_4f1cf62ca97167ffc297dc1ff6c\``);
        await queryRunner.query(`ALTER TABLE \`conductor_empresa\` DROP FOREIGN KEY \`FK_c8f8f2fd18cb662774e35dd2b5c\``);
        await queryRunner.query(`ALTER TABLE \`turnos\` DROP FOREIGN KEY \`FK_321cdd32b08af8ecab080d49f04\``);
        await queryRunner.query(`ALTER TABLE \`turnos\` DROP FOREIGN KEY \`FK_3db03ec6ba62996743b23a24b7e\``);
        await queryRunner.query(`ALTER TABLE \`conductores\` DROP FOREIGN KEY \`FK_bc0266d66cf1bb0692fe14a01c6\``);
        await queryRunner.query(`ALTER TABLE \`ciudadano\` DROP FOREIGN KEY \`FK_fdadb55def4c5fbce66f3d392a4\``);
        await queryRunner.query(`ALTER TABLE \`direccion\` DROP FOREIGN KEY \`FK_df373932bc5a6a0bbaaecbccea7\``);
        await queryRunner.query(`ALTER TABLE \`boleto\` DROP FOREIGN KEY \`FK_825ae17acb796f8a8d4b2aed798\``);
        await queryRunner.query(`ALTER TABLE \`boleto\` DROP FOREIGN KEY \`FK_b3182517ed67a8d0739e2c9ca59\``);
        await queryRunner.query(`ALTER TABLE \`boleto\` DROP FOREIGN KEY \`FK_9e9d89c940f3e190d66cf1868d5\``);
        await queryRunner.query(`ALTER TABLE \`boleto\` DROP FOREIGN KEY \`FK_60cd723c3b608aaa0059b46a909\``);
        await queryRunner.query(`ALTER TABLE \`boleto\` DROP FOREIGN KEY \`FK_c5318ccf8289d5deb313d19bd3a\``);
        await queryRunner.query(`ALTER TABLE \`historial\` DROP FOREIGN KEY \`FK_50bd5f52ae58b1b2efc83d5f834\``);
        await queryRunner.query(`ALTER TABLE \`metodo_pago_ciudadano\` DROP FOREIGN KEY \`FK_16416e7ac48e2b3bb6898d1080c\``);
        await queryRunner.query(`ALTER TABLE \`metodo_pago_ciudadano\` DROP FOREIGN KEY \`FK_3448ebaef063722c5900c2fac68\``);
        await queryRunner.query(`ALTER TABLE \`programacion\` DROP FOREIGN KEY \`FK_51ba4fea596d405565625520a21\``);
        await queryRunner.query(`ALTER TABLE \`programacion\` DROP FOREIGN KEY \`FK_1fefc0e6ae411f0be01cd22a484\``);
        await queryRunner.query(`ALTER TABLE \`bus\` DROP FOREIGN KEY \`FK_93ff3c614d8a889bb6d310ed3a2\``);
        await queryRunner.query(`ALTER TABLE \`incidente_bus\` DROP FOREIGN KEY \`FK_61db9713f26ed84bf3087522f66\``);
        await queryRunner.query(`ALTER TABLE \`incidente_bus\` DROP FOREIGN KEY \`FK_58c5047804eba8562637d817c5c\``);
        await queryRunner.query(`ALTER TABLE \`foto\` DROP FOREIGN KEY \`FK_c4fd0e65ba0905cb36931c0b78c\``);
        await queryRunner.query(`ALTER TABLE \`gps\` DROP FOREIGN KEY \`FK_8f4db1f562e86ccd755281edc60\``);
        await queryRunner.query(`ALTER TABLE \`ruta_nodo\` DROP FOREIGN KEY \`FK_eee2cae961894022e049d8a13fc\``);
        await queryRunner.query(`ALTER TABLE \`ruta_nodo\` DROP FOREIGN KEY \`FK_50541059952803106dddc9e6aa0\``);
        await queryRunner.query(`ALTER TABLE \`paradero\` DROP FOREIGN KEY \`FK_dcdf9847867f04a91df1d7fe5a2\``);
        await queryRunner.query(`ALTER TABLE \`ruta_paradero\` DROP FOREIGN KEY \`FK_3060cb5c90d2504a25523504377\``);
        await queryRunner.query(`ALTER TABLE \`ruta_paradero\` DROP FOREIGN KEY \`FK_72d54fccf60b6ea346ad3dc4469\``);
        await queryRunner.query(`ALTER TABLE \`destinatario_persona\` DROP FOREIGN KEY \`FK_beea970ff14af9f3a15fcb0f19c\``);
        await queryRunner.query(`ALTER TABLE \`destinatario_persona\` DROP FOREIGN KEY \`FK_7fa2d6e9f046968c997957edd10\``);
        await queryRunner.query(`ALTER TABLE \`mensaje\` DROP FOREIGN KEY \`FK_b1d45e3d87c8eee37bc4e2b21ff\``);
        await queryRunner.query(`ALTER TABLE \`destinatario_grupo\` DROP FOREIGN KEY \`FK_2c808d4acbc54788ffe55e9189b\``);
        await queryRunner.query(`ALTER TABLE \`destinatario_grupo\` DROP FOREIGN KEY \`FK_c7f0f15e7fa8ca157302017f13f\``);
        await queryRunner.query(`ALTER TABLE \`grupo_persona\` DROP FOREIGN KEY \`FK_ebc9bb021507e8b8c644bf78ea2\``);
        await queryRunner.query(`ALTER TABLE \`grupo_persona\` DROP FOREIGN KEY \`FK_9ea3f0fa83ef78bb8294060216a\``);
        await queryRunner.query(`DROP INDEX \`IDX_4f1cf62ca97167ffc297dc1ff6\` ON \`conductor_empresa\``);
        await queryRunner.query(`DROP INDEX \`IDX_c8f8f2fd18cb662774e35dd2b5\` ON \`conductor_empresa\``);
        await queryRunner.query(`DROP TABLE \`conductor_empresa\``);
        await queryRunner.query(`DROP TABLE \`turnos\``);
        await queryRunner.query(`DROP INDEX \`REL_bc0266d66cf1bb0692fe14a01c\` ON \`conductores\``);
        await queryRunner.query(`DROP INDEX \`IDX_a01e7172ea361195be58ab5962\` ON \`conductores\``);
        await queryRunner.query(`DROP TABLE \`conductores\``);
        await queryRunner.query(`DROP INDEX \`IDX_22bb7195753df2b9f436e5b146\` ON \`personas\``);
        await queryRunner.query(`DROP INDEX \`IDX_6019651944f62d09f56ff66f60\` ON \`personas\``);
        await queryRunner.query(`DROP INDEX \`IDX_cabd31e2b3c629c2060912e972\` ON \`personas\``);
        await queryRunner.query(`DROP TABLE \`personas\``);
        await queryRunner.query(`DROP INDEX \`REL_fdadb55def4c5fbce66f3d392a\` ON \`ciudadano\``);
        await queryRunner.query(`DROP TABLE \`ciudadano\``);
        await queryRunner.query(`DROP INDEX \`REL_df373932bc5a6a0bbaaecbccea\` ON \`direccion\``);
        await queryRunner.query(`DROP TABLE \`direccion\``);
        await queryRunner.query(`DROP TABLE \`boleto\``);
        await queryRunner.query(`DROP TABLE \`historial\``);
        await queryRunner.query(`DROP TABLE \`metodo_pago_ciudadano\``);
        await queryRunner.query(`DROP TABLE \`metodo_pago\``);
        await queryRunner.query(`DROP TABLE \`programacion\``);
        await queryRunner.query(`DROP INDEX \`IDX_fb7ea3a64d22d5276573f22dbd\` ON \`bus\``);
        await queryRunner.query(`DROP TABLE \`bus\``);
        await queryRunner.query(`DROP TABLE \`incidente_bus\``);
        await queryRunner.query(`DROP TABLE \`foto\``);
        await queryRunner.query(`DROP TABLE \`incidente\``);
        await queryRunner.query(`DROP INDEX \`REL_8f4db1f562e86ccd755281edc6\` ON \`gps\``);
        await queryRunner.query(`DROP TABLE \`gps\``);
        await queryRunner.query(`DROP INDEX \`IDX_51ac4482e14d7afaa64eab9c5a\` ON \`empresa\``);
        await queryRunner.query(`DROP TABLE \`empresa\``);
        await queryRunner.query(`DROP INDEX \`IDX_1e33ae47cf8a8048e14db83ebc\` ON \`ruta\``);
        await queryRunner.query(`DROP TABLE \`ruta\``);
        await queryRunner.query(`DROP TABLE \`ruta_nodo\``);
        await queryRunner.query(`DROP TABLE \`nodo\``);
        await queryRunner.query(`DROP INDEX \`IDX_a47bf8f07546ec7ce88ba4f027\` ON \`paradero\``);
        await queryRunner.query(`DROP TABLE \`paradero\``);
        await queryRunner.query(`DROP TABLE \`ruta_paradero\``);
        await queryRunner.query(`DROP TABLE \`destinatario_persona\``);
        await queryRunner.query(`DROP TABLE \`mensaje\``);
        await queryRunner.query(`DROP TABLE \`destinatario_grupo\``);
        await queryRunner.query(`DROP TABLE \`grupo\``);
        await queryRunner.query(`DROP TABLE \`grupo_persona\``);
    }

}
