spring.application.name=ms-security
server.port=${PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI}

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

recaptcha.secret=${RECAPTCHA_SECRET_KEY}
recaptcha.min-score=${RECAPTCHA_MIN_SCORE}